image: gcc:4.9

before_script:
    - 'which git || ( apt-get update -y && apt-get install git -y )'
    - git submodule init
    - git submodule update
    - cd test

stages:
    - static test
    - build
    - test

build:
    stage: build
    script:
        - make
    artifacts:
        paths:
        - test
        expire_in: 5 minutes

test:
    stage: test
    script:
        - ./test -d yes

static:
    image: walberla/cppcheck
    stage: static test
    script:
        - cppcheck --enable=warning,style,performance -j 2 ../netHelper.hpp ../loopTimer.hpp ../circular_buffer.hpp
