image: gcc:4.9

before_script:
    - git submodule init
    - git submodule update
    - cd test

stages:
    - build
    - test

build:
    stage: build
    script:
        - make
    artifacts:
        paths:
        - test
        expire_in: 5 minutes

test:
    stage: test
    script:
        - ./test -d yes
