before_script:
    - cd test

stages:
    - build
    - test

build:
    stage: build
    script:
        - make
    artifacts:
        paths:
        - test
        expire_in: 10 minutes

test:
    stage: test
    script:
        - ./test
